name: healthy_plan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.0.4
  firebase_storage: ^13.0.0
  cloudinary_public: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  assets:
    - lib/assets/Logo.png

  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"
